version: "3"
services:
  tf:
#    image: latest-jupyter
    container_name: tf-jpy-lat
    build:
      context: ./
      dockerfile: ./data/dockerfile
    tty: true
    ports:
      - "8888:8888"
    volumes:
      - ../Note:/home/note #:z